;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Silent Hill 4 - The Room (GOG)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     4.0.2
; Xidi Form:        DInput8
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          samuelgr
; Last Modified:    07/24/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type            = SH4

[CustomMapper:SH4]
Template        = StandardGamepad

ButtonA         = Button(2)
ButtonB         = Button(3) 
ButtonX         = Button(1)
ButtonY         = Button(4)

; Right Stick
StickRightX     = Axis(RotX)
StickRightY     = Axis(RotY)
