# Instruction:
# - Move the file to "<Silent Hill 3 game folder>\savedata" folder.
#
# NOTE: This configuration follows the PS2 controls.

################################################
# Key assigns
################################################

front_move=button12
back_move=button14
left_turn=button15
right_turn=button13
map=button3
dash=button2
light=button1
action=button0
left_moev=button4
right_moev=button5
searh_view=button6
ready=button7
zoom=button10
sub_equip=button11
item=button8
pause=button9
enter=button0
cancel=button1
skip=button8
left_x=analog0
left_y=analog1
right_x=analog2
right_y=analog5
left=pov0
right=pov1
front_move=W
back_move=S
left_turn=Q
right_turn=E
map=M
dash=LSHIFT
light=L
action=SPACE
left_moev=A
right_moev=D
searh_view=TAB
ready=B
zoom=Z
sub_equip=H
item=I
pause=ESCAPE
enter=RETURN
cancel=ESCAPE
skip=ESCAPE
qsave=F5
qload=F9
cup=UP
cdown=DOWN
cleft=LEFT
cright=RIGHT
