;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; One Piece: Pirate Warriors 3
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     v5.0.0
; Xidi Form:        dinput8.dll + Xidi.32.dll
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          ProjectXsent
; Last Modified:    09/18/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type = OPPW3

[Log]
Enabled = no
Level = 4

[CustomMapper:OPPW3]
Template = StandardGamepad

ButtonA             = Button(3)
ButtonB             = Button(4)
ButtonX             = Button(1)
ButtonY             = Button(2)
