;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Final Fantasy VII (2013 Steam)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     v5.0.0
; Xidi Form:        dinput.dll + dinput8.dll + winmm.dll + Xidi.32.dll
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          ProjectXsent
; Last Modified:    06/29/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type = FF7

[CustomMapper:FF7]
Template = DigitalGamepad

ButtonA = Button(2)
ButtonB = Compound(Button(3), Keyboard(X))
ButtonB = Button(3)
ButtonX = Button(1)
ButtonY = Button(4)
