;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Prince of Persia: The Sands of Time
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     5.0.0
; Xidi Form:        dinput8.dll + Xidi.32.dll
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          vini1264
; Last Modified:    06/29/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Properties]
SaturationPercentStickLeft = 75
SaturationPercentStickRight = 75

[Mapper]
Type = PoPTSoT

[Log]
Enabled = no
Level = 4

[CustomMapper:PoPTSot]
Template = StandardGamepad

ButtonStart     = Keyboard(Esc)
; This will allow the Start Button to Pause the game.

StickRightX     = Axis(RotX)
StickRightY     = Axis(RotY)
