;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Prince of Persia: The Sands of Time
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     5.0.0
; Xidi Form:        dinput8.dll + Xidi.32.dll
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          vini1264
; Last Modified:    09/14/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Properties]
MouseSpeedScalingFactorPercent = 40
SaturationPercentStickLeft     = 75
SaturationPercentStickRight    = 75

[Mapper]
Type = PoPTSoT

[CustomMapper:PoPTSoT]
Template = StandardGamepad

DpadUp          = MouseAxis(Y, -)
DpadDown        = MouseAxis(Y, +)
DpadLeft        = MouseAxis(X, -)
DpadRight       = MouseAxis(X, +)
; This will allow to move the Mouse using D-Pad when navigating the menu

ButtonBack      = MouseButton(Left)
; Press Back/View/Select/Share button to click

ButtonStart     = Keyboard(Esc)
; Press Menu/Start/Option button to pause the game

StickRightX     = Axis(RotX)
StickRightY     = Axis(RotY)
