;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Resident Evil (1998) GOG
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     5.0.0
; Xidi Form:        dinput.dll + winmm.dll + Xidi.32.dll
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          ProjectXsent
; Last Modified:    06/29/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type = RE2Classic

[CustomMapper:RE2Classic]
Template = DigitalGamepad

ButtonRS = Keyboard(F9)
; This will allow the RS/R3 Button to Quit to Main Menu/game.
