;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sonic Adventure DX (Steam)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     5.0.0
; Xidi Form:        dinput8
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          ProjectXsent
; Last Modified:    09/18/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type            = SonicAdventureDX

[Log]
Enabled = no
Level = 4

[CustomMapper:SonicAdventureDX]
Template = DigitalGamepad

[Workarounds]
ActiveVirtualControllerMask = 0x01
; Without it, there will be Xidi Virtual Controller 1 and 2 options in the configuration tool
