;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sonic Adventure DX
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     5.0.0
; Xidi Form:        dinput8
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          ProjectXsent
; Last Modified:    09/18/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type            = SonicAdventureDX

[Log]
Enabled = no
Level = 4

[CustomMapper:SonicAdventureDX]
Template = DigitalGamepad

ButtonA             = Button(3)
ButtonB             = Button(1)
ButtonX             = Button(4)
ButtonY             = Button(2)

ButtonLB            = Button(7)
ButtonRB            = Button(5)
TriggerLT           = Null
