;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Final Fantasy VIII (2013 Steam)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     v5.0.0
; Xidi Form:        dinput.dll + dinput8.dll + Xidi.32.dll
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          ProjectXsent
; Last Modified:    08/13/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type = FF8

[CustomMapper:FF8]
Template = DigitalGamepad

ButtonA = Button(2)
ButtonB = Button(3)
ButtonX = Button(1)
ButtonY = Button(4)

ButtonRS = Keyboard(X)
; Pressing RS/R3 Button will allow you to proceed past the intro FMVs and the "Keyboard" prompt before reaching the Title Menu

[Workarounds]
PollReturnCode = 0
