;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Silent Hill 2: Director's Cut
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Xidi Version:     v5.0.0
; Xidi Form:        dinput8.dll + Xidi.32.dll
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Authors:          elishacloud
; Last Modified:    07/12/2026
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Mapper]
Type = SH2

[Log]
Enabled = no
Level = 4

[CustomMapper:SH2]
Template = StandardGamepad

ButtonA             = Button(2)
ButtonB             = Button(3)
ButtonX             = Button(1)
ButtonY             = Button(4)
